Login format sh
sal59265/connectFriends pull request #5
Opened 2022-02-02 00:42 UTC by seolheekang1221

# Link to Trello
- Link goes here

# Proposed Changes
- change 1
- change 2

# Additional Info
- any additional information or context

# Checklist
- [o] Comments in the code
- [] Remove console.logs
- [] Clean code

2022-02-02 03:14 UTC, sal59265 approved these changes
There is a conflict, please resolve before merging.

2022-02-04 01:01 UTC, jingu-k816 commented on client/src/App.js
> +      console.log("Success");
please remove console.log

2022-02-04 01:01 UTC, jingu-k816 commented on client/src/App.js
> +      console.log("your password is incorret");
don't need console log here as well

2022-02-04 01:04 UTC, jingu-k816 requested changes
We need to re do the login page from scratch

2022-02-04 01:04 UTC, jingu-k816 commented on client/src/App.js
> +      forms.email == loginUser.email &&
type checking should be triple equals not double

2022-02-04 01:04 UTC, jingu-k816 commented on client/src/App.js
> +      forms.password == loginUser.password
same comment as above

2022-02-04 01:04 UTC, jingu-k816 commented on client/src/App.js
> +    console.log(forms);
no console.logs

2022-02-11 00:29 UTC, closed without merging